<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="product-review-wrapepr">
    <div data-role="loader" class="loading-mask review-list-loading" style="display: none;">
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>">
        </div>
    </div>
    <div id="product-review-container"></div>
    <?php echo $block->getChildHtml(); ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?php /* @escapeNotVerified */ echo $block->getProductReviewUrl(); ?>"
            }
        }
    }
</script>


<script>
    require([
        'jquery'
    ], function ($) {
        if ($('.review-toolbar a')) {
            $(document).on('click', '.review-toolbar a', function (event) {
                event.preventDefault();
                $('.loading-mask.review-list-loading').show();
                //customer-reviews
                $.ajax({
                    url: $(this).attr('href'),
                    type: 'get',
                    success: function (data) {
                        $('#product-review-container').html(data);
                        $('.loading-mask.review-list-loading').hide();
                    }
                });
            })
        }

    });
</script>