<div class="footer-main-wrapper">
	<div class="footer-top">
		<div class="footer-top-inner">
			<div class="footer-links">
				<?php echo $block->getChildHtml('cms.footer.links'); ?>
			</div>
			<div class="footer-right">
				<?php echo $block->getChildHtml('subscribe'); ?>
				<div class="footer-social">
					<?php echo $block->getChildHtml('footer.social'); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="footer-bottom-inner">
			<div class="footer-copyright">
				<?php echo $block->getChildHtml('copyright'); ?>
			</div>
			<div class="footer-banks">
				<?php echo $block->getChildHtml('footer.banks'); ?>
			</div>
		</div>
	</div>
</div>