<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<?php if(!$customerSession->isLoggedIn()): ?>
    <p class="welcome welcome-notlogin"><?php echo $welcomeMessage; ?></p>
<?php else: ?>
    <p class="welcome welcome-login"><?php echo __('Hi %1!',$customerSession->getCustomer()->getName()); ?></p>
<?php endif; ?>