<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $columnCount = 6;
    $type = 'widget-viewed';
    $mode = 'grid';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_images_names_widget';
    $title = __('Recently Viewed');
    $items = $block->getRecentlyViewedProducts();

    $showWishlist = false;
    $showCompare = false;
    $showCart = false;
    $rating = false;
    $description = false;
} else {
    return;
}
?>
<div class="block widget block-product-view-list block-viewed-products-<?php /* @escapeNotVerified */ echo $mode; ?>">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        <p class="viewed-view-all">
            <a href="#" class="button btn-all"><?php echo __('View All Products'); ?></a>
        </p>
    </div>
    <div class="block-content">
        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <ol class="products list items product-items">
                <?php $iterator = 0; ?>
                <?php foreach ($items as $_product): ?>
                    <?php
                    $iterator++;
                    $moreClassItem = '';
                    if ($iterator % $columnCount == 1) {
                        $moreClassItem .= ' first';
                    } elseif ($iterator % $columnCount == 0) {
                        $moreClassItem .= ' last';
                    }
                    if ($iterator % 2 == 0) {
                        $moreClassItem .= ' even';
                    } else {
                        $moreClassItem .= ' odd';
                    }
                    $available = '';
                    ?>
                    <li class="item product product-item<?php echo $moreClassItem; ?>">
                        <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>" class="product photo product-item-photo">
                                <?php echo $block->getImage($_product, $image)->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_product->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>">
                                        <?php echo $block->escapeHtml($_product->getName()) ?></a>
                                </strong>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true) ?>
                                <?php endif; ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product); ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
</div>
