
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
/** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
if ($exist = count($block->getItemCollection()->getItems())) {
    $type = 'upsell';
    $class = $type;

    $image = 'upsell_products_list';
    $title = __('You may also buy!');
    $items = $block->getItemCollection()->getItems();
    $limit = $block->getItemLimit('upsell');
    $shuffle = 0;

    $showWishlist = false;
    $showCompare = false;
    $showCart = false;
    $templateType = null;
    $description = false;
    $canItemsAddToCart = false;
    $columnCount = 1;
} else {
    return;
}
?>

<div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class ?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class ?>-heading">
        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <ol class="products list items product-items">
                <?php $iterator = 0; ?>
                <?php foreach ($items as $_item): ?>
                    <?php
                    $iterator++;
                    $moreClassItem = '';
                    if ($iterator % $columnCount == 1) {
                        $moreClassItem .= ' first';
                    } elseif ($iterator % $columnCount == 0) {
                        $moreClassItem .= ' last';
                    }
                    if ($iterator % 2 == 0) {
                        $moreClassItem .= ' even';
                    } else {
                        $moreClassItem .= ' odd';
                    }
                    $available = '';
                    ?>
                    <li class="item product product-item<?php echo $moreClassItem; ?>">
                        <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                </strong>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
            <div class="upsell-view-all">
                <a href="#" class="button btn-all"><?php echo __('View All Products'); ?></a>
            </div>
        </div>
    </div>
</div>

