<div class="fl-box">
	<h3 class="ec-label">
		<span>ABOUT</span>
	</h3>
	<ul class="ec-box">
		<li>
			<a href="{{store url="about-us"}}">About us</a>
		</li>
		<li>
			<a href="{{store url="contact-us"}}">Contact us</a>
		</li>
		<li>
			<a href="{{store url="customer/account"}}">My Account</a>
		</li>
		<li>
			<a href="{{store url="orders-history"}}">Orders history</a>
		</li>
		<li>
			<a href="{{store url="shipping-information"}}">Shipping information</a>
		</li>
		<li>
			<a href="{{store url="return-policy"}}">Return policy </a>
		</li>
		<li>
			<a href="{{store url="faq"}}">FAQ</a>
		</li>
	</ul>
</div>

<div class="fl-box">
	<h3 class="ec-label">
		<span>PRODUCTS</span>
	</h3>
	<ul class="ec-box">
		<li>
			<a href="{{store url=""}}">Category 01</a>
		</li>
		<li>
			<a href="{{store url="wines.html"}}">WINES</a>
		</li>
		<li>
			<a href="{{store url="olives.html"}}">OLIVES</a>
		</li>
		<li>
			<a href="{{store url="nuts"}}">NUTS</a>
		</li>
		<li>
			<a href="{{store url="marmalade.html"}}">Marmalade</a>
		</li>
	</ul>
</div>

<div class="fl-box">
	<h3 class="ec-label">
		<span>PRODUCTS</span>
	</h3>
	<ul class="ec-box">
		<li>
			<a href="{{store url=""}}">Category 01</a>
		</li>
		<li>
			<a href="{{store url="wines.html"}}">WINES</a>
		</li>
		<li>
			<a href="{{store url="olives.html"}}">OLIVES</a>
		</li>
		<li>
			<a href="{{store url="nuts"}}">NUTS</a>
		</li>
		<li>
			<a href="{{store url="marmalade.html"}}">Marmalade</a>
		</li>
	</ul>
</div>