<a href="#" class="icon icon-facebook">
	<span>fb</span>
</a>
<a href="#" class="icon icon-pinterest">
	<span>pinterest</span>
</a>
<a href="#" class="icon icon-in">
	<span>in</span>
</a>
<a href="#" class="icon icon-googleplus">
	<span>googleplus</span>
</a>
<a href="#" class="icon icon-youtube">
	<span>youtube</span>
</a>
<a href="#" class="icon icon-instagram">
	<span>instagram</span>
</a>
